"""Delivery: running the Delivery_Workflow's configured stage commands.

A workflow is configuration, not plugin code: each stage maps to a list of argv
templates, and the engine substitutes run variables into them and runs them with
no shell. That is what lets a pull-request workflow, an organization's own review
system, and a plain local build all be the same mechanism.

The module boundaries follow the trust boundary:

* :mod:`.templates` parses templates once and substitutes values as single argv
  elements. This is where attacker-authored text is made inert.
* :mod:`.variables` assembles a run's variable set from the run context plus the
  project's custom names.
* :mod:`.workflow` resolves which commands a stage runs, from which
  configuration layer, and answers whether a project configured a workflow at
  all — the zero-configuration case that caps autonomy at execution.
* :mod:`.stages` validates a whole stage, then executes it.
* :mod:`.integration` holds the integration floor: the protected branch set, the
  workflow ceiling on autonomy, and the two independent gates an unattended merge
  must both pass.
* :mod:`.isolation` gives each run a working tree of its own and refuses to hand
  one tree to two runs.
* :mod:`.flow` orders the stages — isolate before execution, publish only after
  verification, fix rounds bounded by the retry limit — and is the one entry
  point both an autonomous run and an explicit human request start, so neither
  can run a different set of stages, variables, or gates than the other. It also
  notifies the outcome of every executed stage when a delivery ends.
"""

from __future__ import annotations

from .flow import (
    DELIVERY_FLOW_STAGES,
    EVENT_FIX_DISPATCH,
    EVENT_GATE,
    EVENT_GATES,
    EVENT_INTEGRATION,
    EVENT_OUTCOME,
    EVENT_PUBLISHED,
    EVENT_REQUESTED,
    EVENT_STAGE,
    MAX_ADDRESS_CHARS,
    MAX_DEPLOYMENT_ADDRESSES,
    MAX_GATE_OUTPUT_CHARS,
    NO_GATES_REASON,
    NO_NOTIFIER_REASON,
    PUBLISH_STAGE,
    QUALITY_GATE_PRESETS,
    SUBMIT_STAGE,
    UNNAMED_REQUESTER_REASON,
    VERIFY_RETRY_LIMIT_SETTING,
    VERIFY_STAGE,
    AuditRecorder,
    DeliveryNotice,
    DeliveryOutcome,
    DeliveryPipeline,
    DeliveryRun,
    FixDispatch,
    FixTaskDispatcher,
    GateRound,
    GateRun,
    Notifier,
    OnSubmitted,
    QualityGate,
    VerifyAttempt,
    gate_presets,
    load_quality_gates,
)
from .integration import (
    PROTECTED_BRANCHES_FIELD,
    REASON_DELIVERY_FAILED,
    REASON_LADDER,
    REASON_NO_TARGET,
    REASON_POSTURE,
    REASON_VERIFY,
    DeliveryAuthority,
    IntegrationDecision,
    ProtectedBranches,
    evaluate_integration,
    resolve_authority,
    resolve_protected_branches,
)
from .isolation import (
    BRANCH_PREFIX,
    DEPLOYMENT_KIND,
    DISPOSABLE_KINDS,
    GIT_ISOLATE_COMMANDS,
    ISOLATED_PATH_VARIABLE,
    MAX_SLUG_CHARS,
    TEMP_COPY_KIND,
    WORKTREE_KIND,
    WorkspaceBroker,
    WorkspaceClaim,
    WorkspaceLedger,
    WorkspacePlan,
    git_isolate_commands,
    isolated_context,
    plan_workspace,
    slugify,
)
from .preset_display import (
    MAX_PRESET_NAME_CHARS,
    StageOrigin,
    StageSource,
    stage_origins,
)
from .stages import (
    MAX_CAPTURED_CHARS,
    STAGE_TIMEOUT_SETTING,
    TRUNCATION_NOTICE,
    CommandOutcome,
    CommandResult,
    CommandRunner,
    StageExecutor,
    StageOutcome,
    StageResult,
    run_argv,
)
from .teardown import (
    EVENT_TEARDOWN,
    REASON_ALREADY_GONE,
    REASON_NO_ROOT,
    REASON_NO_STAGE,
    REASON_NOT_DISPOSABLE,
    REASON_OUTSIDE_ROOT,
    REMOVAL_TIMEOUT_S,
    TEARDOWN_STAGE,
    StageRunner,
    TeardownReport,
    WorkspaceCleanup,
    WorkspaceJanitor,
)
from .templates import (
    VARIABLE_NAME_PATTERN,
    ArgumentTemplate,
    CommandTemplate,
    MissingVariableError,
    TemplateError,
    VariableRef,
    has_value,
)
from .variables import RUN_CONTEXT_VARIABLES, RunContext, VariableError, build_variables
from .workflow import (
    ISOLATE_STAGE,
    STAGES_KEY,
    VARIABLES_KEY,
    WORKFLOW_PRESET_NAMES,
    WORKFLOW_PRESETS,
    ZERO_CONFIG_AUTONOMY_CEILING,
    DeliveryWorkflow,
    PresetSelection,
    StageCommands,
    cap_autonomy,
    workflow_preset_definition,
    workflow_presets,
)

__all__ = [
    "BRANCH_PREFIX",
    "DELIVERY_FLOW_STAGES",
    "DEPLOYMENT_KIND",
    "DISPOSABLE_KINDS",
    "EVENT_FIX_DISPATCH",
    "EVENT_GATE",
    "EVENT_GATES",
    "EVENT_INTEGRATION",
    "EVENT_OUTCOME",
    "EVENT_PUBLISHED",
    "EVENT_REQUESTED",
    "EVENT_STAGE",
    "EVENT_TEARDOWN",
    "GIT_ISOLATE_COMMANDS",
    "ISOLATED_PATH_VARIABLE",
    "ISOLATE_STAGE",
    "MAX_ADDRESS_CHARS",
    "MAX_CAPTURED_CHARS",
    "MAX_DEPLOYMENT_ADDRESSES",
    "MAX_GATE_OUTPUT_CHARS",
    "MAX_PRESET_NAME_CHARS",
    "MAX_SLUG_CHARS",
    "NO_GATES_REASON",
    "NO_NOTIFIER_REASON",
    "PROTECTED_BRANCHES_FIELD",
    "PUBLISH_STAGE",
    "QUALITY_GATE_PRESETS",
    "REASON_ALREADY_GONE",
    "REASON_DELIVERY_FAILED",
    "REASON_LADDER",
    "REASON_NOT_DISPOSABLE",
    "REASON_NO_ROOT",
    "REASON_NO_STAGE",
    "REASON_NO_TARGET",
    "REASON_OUTSIDE_ROOT",
    "REASON_POSTURE",
    "REASON_VERIFY",
    "REMOVAL_TIMEOUT_S",
    "RUN_CONTEXT_VARIABLES",
    "STAGES_KEY",
    "STAGE_TIMEOUT_SETTING",
    "SUBMIT_STAGE",
    "TEARDOWN_STAGE",
    "TEMP_COPY_KIND",
    "TRUNCATION_NOTICE",
    "UNNAMED_REQUESTER_REASON",
    "VARIABLES_KEY",
    "WORKFLOW_PRESET_NAMES",
    "WORKFLOW_PRESETS",
    "VARIABLE_NAME_PATTERN",
    "VERIFY_RETRY_LIMIT_SETTING",
    "VERIFY_STAGE",
    "WORKTREE_KIND",
    "ZERO_CONFIG_AUTONOMY_CEILING",
    "ArgumentTemplate",
    "AuditRecorder",
    "CommandOutcome",
    "CommandResult",
    "CommandRunner",
    "CommandTemplate",
    "DeliveryAuthority",
    "DeliveryNotice",
    "DeliveryOutcome",
    "DeliveryPipeline",
    "DeliveryRun",
    "DeliveryWorkflow",
    "FixDispatch",
    "FixTaskDispatcher",
    "GateRound",
    "GateRun",
    "IntegrationDecision",
    "MissingVariableError",
    "Notifier",
    "OnSubmitted",
    "ProtectedBranches",
    "QualityGate",
    "RunContext",
    "PresetSelection",
    "StageCommands",
    "StageExecutor",
    "StageOrigin",
    "StageOutcome",
    "StageResult",
    "StageRunner",
    "StageSource",
    "TeardownReport",
    "TemplateError",
    "VariableError",
    "VariableRef",
    "VerifyAttempt",
    "WorkspaceBroker",
    "WorkspaceCleanup",
    "WorkspaceClaim",
    "WorkspaceJanitor",
    "WorkspaceLedger",
    "WorkspacePlan",
    "build_variables",
    "cap_autonomy",
    "workflow_preset_definition",
    "workflow_presets",
    "evaluate_integration",
    "gate_presets",
    "git_isolate_commands",
    "has_value",
    "isolated_context",
    "load_quality_gates",
    "plan_workspace",
    "resolve_authority",
    "resolve_protected_branches",
    "run_argv",
    "slugify",
    "stage_origins",
]
