"""Spec engine configuration: schema, bundled defaults, and effective values.

Import from this package rather than its modules; the split between the setting
registry, the schema, the resolver, and the store is an implementation detail.

    from ...engine.config import ConfigStore, DASHBOARD_SURFACE

    store = ConfigStore()
    ceiling = store.effective("budget.run_ceiling_credits", project="acme")
    ceiling.value    # 5.0
    ceiling.origin   # ValueOrigin.BUNDLED_DEFAULT
    store.write({"limits": {"task_retry_limit": 4}}, surface=DASHBOARD_SURFACE)
"""

from __future__ import annotations

from .advisories import (
    AGENT_MISSING_ENGINE_TOOLS,
    AGENT_NOT_INSTALLED,
    AUTO_INTEGRATE_SETTING,
    AUTO_INTEGRATE_WITHOUT_VERIFY,
    CONFIG_ACKNOWLEDGMENT_EVENT,
    CONFIG_WARNING_EVENT,
    PUBLIC_SOURCE_AUTONOMY,
    Acknowledgment,
    ConfigWarning,
    WarningRecorder,
    acknowledge,
    document_warnings,
    record_config_warnings,
)
from .agent_surface import (
    ENGINE_MCP_SERVER,
    AgentSurfaceLookup,
    AgentToolSurface,
    DiskAgentSurfaces,
    agent_directories,
    disk_lookup,
)
from .effective import EffectiveValue, ValueOrigin, resolve, resolve_all
from .profiles import (
    PROJECT_PROFILE_FIELD,
    CostProfile,
    RoleAssignment,
    profile,
    profile_pin,
    profiles,
    selected_profile,
    selected_profile_name,
)
from .schema import (
    AUTONOMY_LEVELS,
    CONFIG_ONLY_PATHS,
    CURRENT_VERSION,
    DELEGABLE_CAPABILITIES,
    DELIVERY_STAGES,
    ENGINE_FLOOR_CAPABILITIES,
    GATE_POSITIONS,
    GATE_SEVERITIES,
    ITEM_LIFECYCLE_EVENTS,
    LEAST_TRUSTED_CLASS,
    PROFILE_SETTING_GROUPS,
    PROFILE_SETTING_KEYS,
    PROJECT_FIELDS,
    ROLES,
    SECTIONS,
    SOURCE_FIELDS,
    SPEC_TYPES,
    SUBMITTER_CLASSES,
    TRANSPORTS,
    VERSION_KEY,
    WILDCARD_KEY,
    ConfigError,
    ConfigValidationError,
    config_only_paths,
    validate_config_document,
)
from .settings import SETTINGS, Scope, Setting, default_of, lookup, settings_in_scope
from .store import (
    APP_NAME,
    CONFIG_FILENAME,
    DASHBOARD_SURFACE,
    SETUP_ASSISTANT_SURFACE,
    ConfigLoadError,
    ConfigStore,
    ConfigWriteRefused,
    ConfigWriteSurface,
    default_root,
)

__all__ = [
    "AGENT_MISSING_ENGINE_TOOLS",
    "AGENT_NOT_INSTALLED",
    "APP_NAME",
    "AUTO_INTEGRATE_SETTING",
    "AUTO_INTEGRATE_WITHOUT_VERIFY",
    "AUTONOMY_LEVELS",
    "CONFIG_FILENAME",
    "CONFIG_ONLY_PATHS",
    "CONFIG_ACKNOWLEDGMENT_EVENT",
    "CONFIG_WARNING_EVENT",
    "CURRENT_VERSION",
    "DASHBOARD_SURFACE",
    "DELEGABLE_CAPABILITIES",
    "DELIVERY_STAGES",
    "ENGINE_FLOOR_CAPABILITIES",
    "ENGINE_MCP_SERVER",
    "GATE_POSITIONS",
    "GATE_SEVERITIES",
    "ITEM_LIFECYCLE_EVENTS",
    "LEAST_TRUSTED_CLASS",
    "PROFILE_SETTING_GROUPS",
    "PROFILE_SETTING_KEYS",
    "PROJECT_FIELDS",
    "PROJECT_PROFILE_FIELD",
    "PUBLIC_SOURCE_AUTONOMY",
    "ROLES",
    "SECTIONS",
    "SETTINGS",
    "SETUP_ASSISTANT_SURFACE",
    "SOURCE_FIELDS",
    "SPEC_TYPES",
    "SUBMITTER_CLASSES",
    "TRANSPORTS",
    "VERSION_KEY",
    "WILDCARD_KEY",
    "Acknowledgment",
    "AgentSurfaceLookup",
    "AgentToolSurface",
    "ConfigError",
    "ConfigLoadError",
    "ConfigStore",
    "ConfigValidationError",
    "ConfigWarning",
    "ConfigWriteRefused",
    "ConfigWriteSurface",
    "CostProfile",
    "DiskAgentSurfaces",
    "EffectiveValue",
    "RoleAssignment",
    "Scope",
    "Setting",
    "ValueOrigin",
    "WarningRecorder",
    "acknowledge",
    "agent_directories",
    "config_only_paths",
    "default_of",
    "default_root",
    "disk_lookup",
    "document_warnings",
    "lookup",
    "profile",
    "profile_pin",
    "profiles",
    "record_config_warnings",
    "resolve",
    "resolve_all",
    "selected_profile",
    "selected_profile_name",
    "settings_in_scope",
    "validate_config_document",
]
