"""Watchers: turning a configured command into watched items, for free.

A watch source is configuration — a poll command and a field mapping — so
watching a new tracker needs no plugin code. Import from this package rather
than its modules.

    from ...engine.watch import poll_source, poll_tick

    outcome = poll_source(store, "upstream-issues")
    if outcome.found_no_items:
        ...   # true only after a poll that actually ran

The module split follows what each part is responsible for:

* :mod:`.items` — the seven fields a source yields, all of them untrusted text.
* :mod:`.sources` — a source's definition, its enablement, and its field mapping.
* :mod:`.poll` — running the command and reporting health, where an unavailable
  program is never mistaken for an empty backlog.
* :mod:`.lifecycle` — diffing successive polls into new items, reopens, and
  cancellations, and claiming each (item, generation) once.
* :mod:`.dispatch` — routing a claimed item to a project, a spec type, a trust
  class, and an autonomy level, then seeding the run or refusing to.
* :mod:`.tick` — the script cron that runs a tick with no model invocation.
"""

from __future__ import annotations

from .dispatch import (
    ASSOCIATION_CLASSES,
    AUDIT_ITEM_EDIT_IGNORED,
    CLAIM_NAME_TAKEN,
    CLAIM_UNMAPPED,
    DISPATCH_HEADING,
    GLOBAL_CAP_SETTING,
    INTAKE_HEADING,
    MIN_FENCE_LENGTH,
    OCCUPYING_STATES,
    PROJECT_CAP_SETTING,
    QUOTED_DATA_HEADING,
    CancelCascade,
    Capacity,
    CascadeResult,
    CascadeStatus,
    ClassEvidence,
    DispatchRefusal,
    DispatchReport,
    EditAuditResult,
    EditAuditStatus,
    ItemDisposition,
    ItemOutcome,
    QueueDispatch,
    RunSeed,
    RunStarter,
    SeedScreener,
    SourceRoute,
    SubmitterClass,
    audit_mid_run_edits,
    capacity,
    cascade_cancellations,
    class_of_author,
    dispatch_source,
    dispatch_tick,
    drain_queue,
    load_route,
    name_taken_items,
    record_name_taken,
    record_refusal,
    record_unmapped,
    recorded_items,
    submitter_class_of,
    unmapped_items,
)
from .echo import (
    ECHO_FIELD,
    echo_permitted_for,
    echoable_text,
)
from .feedback import (
    AUDIT_ITEM_FEEDBACK,
    FEEDBACK_FIELD,
    FEEDBACK_PRESET_HOSTS,
    FEEDBACK_PRESETS,
    FeedbackOutcome,
    FeedbackPoster,
    FeedbackReport,
    feedback_presets,
    load_feedback,
    post_feedback,
    release_writeback_claim,
)
from .items import CONTENT_DIGEST_FIELDS, ITEM_FIELDS, REQUIRED_ITEM_FIELDS, WatchedItem
from .lifecycle import (
    CLOSED_STATES,
    DISPATCHING_TRANSITIONS,
    FIRST_GENERATION,
    DispatchGate,
    ItemChange,
    Transition,
    WatchAdvance,
    WatchDiff,
    advance_watch,
    claim_dispatch,
    claim_dispatches,
    diff_poll,
    dispatched_generations,
    forget_snapshot,
    generation_key,
    is_open_state,
    record_snapshot,
    release_dispatch_claim,
)
from .poll import (
    MAX_RECORDED_PROBLEMS,
    HealthReason,
    PollOutcome,
    PollStatus,
    RejectedItem,
    poll,
    poll_source,
    poll_sources,
)
from .screening import (
    AUDIT_INTAKE_SCREENING,
    BUNDLED_SCREENING_GUIDANCE,
    SCREENING_FIELD,
    ElementScreening,
    IntakeScreener,
    ScreeningNotifier,
    ScreeningProvider,
    ScreeningReport,
    ScreeningRequest,
    ScreeningResponse,
    ScreeningUnavailable,
    ScreeningVerdict,
    elements_of_item,
    screening_enabled_for,
)
from .sources import (
    ENABLED_KEY,
    FIELD_MAP_KEY,
    INTERVAL_SETTING,
    POLL_KEY,
    POLL_TIMEOUT_SETTING,
    PRESET_KEY,
    WATCH_SOURCE_PRESET_HOSTS,
    WATCH_SOURCE_PRESET_PROGRAMS,
    WATCH_SOURCE_PRESETS,
    FieldMapping,
    WatchSource,
    load_sources,
    poll_interval_s,
    poll_timeout_s,
    source_names,
    watch_source_presets,
)
from .tick import (
    CRON_ENTRY_POINT,
    CRON_JOB_PREFIX,
    CRON_SCRIPT_FILENAME,
    CRON_TIMEOUT_MARGIN_S,
    HOST_SCRIPT_TIMEOUT_S,
    TickReport,
    cron_definitions,
    cron_job_name,
    crons_directory,
    install_tick_script,
    poll_tick,
    run_tick_script,
    source_of_job,
    tick_script_path,
)

__all__ = [
    "ASSOCIATION_CLASSES",
    "AUDIT_INTAKE_SCREENING",
    "AUDIT_ITEM_EDIT_IGNORED",
    "AUDIT_ITEM_FEEDBACK",
    "BUNDLED_SCREENING_GUIDANCE",
    "CLAIM_NAME_TAKEN",
    "CLAIM_UNMAPPED",
    "CLOSED_STATES",
    "CONTENT_DIGEST_FIELDS",
    "CRON_ENTRY_POINT",
    "CRON_JOB_PREFIX",
    "CRON_SCRIPT_FILENAME",
    "CRON_TIMEOUT_MARGIN_S",
    "DISPATCH_HEADING",
    "DISPATCHING_TRANSITIONS",
    "ECHO_FIELD",
    "ENABLED_KEY",
    "FIELD_MAP_KEY",
    "FIRST_GENERATION",
    "GLOBAL_CAP_SETTING",
    "HOST_SCRIPT_TIMEOUT_S",
    "INTAKE_HEADING",
    "INTERVAL_SETTING",
    "ITEM_FIELDS",
    "MAX_RECORDED_PROBLEMS",
    "MIN_FENCE_LENGTH",
    "OCCUPYING_STATES",
    "POLL_KEY",
    "POLL_TIMEOUT_SETTING",
    "PRESET_KEY",
    "PROJECT_CAP_SETTING",
    "QUOTED_DATA_HEADING",
    "REQUIRED_ITEM_FIELDS",
    "SCREENING_FIELD",
    "WATCH_SOURCE_PRESET_HOSTS",
    "WATCH_SOURCE_PRESET_PROGRAMS",
    "WATCH_SOURCE_PRESETS",
    "Capacity",
    "CancelCascade",
    "CascadeResult",
    "CascadeStatus",
    "ClassEvidence",
    "DispatchRefusal",
    "DispatchReport",
    "EditAuditResult",
    "EditAuditStatus",
    "FieldMapping",
    "DispatchGate",
    "HealthReason",
    "ItemChange",
    "ItemDisposition",
    "ItemOutcome",
    "PollOutcome",
    "PollStatus",
    "QueueDispatch",
    "RejectedItem",
    "RunSeed",
    "RunStarter",
    "ElementScreening",
    "IntakeScreener",
    "ScreeningNotifier",
    "ScreeningProvider",
    "ScreeningReport",
    "ScreeningRequest",
    "ScreeningResponse",
    "ScreeningUnavailable",
    "ScreeningVerdict",
    "SeedScreener",
    "SourceRoute",
    "SubmitterClass",
    "TickReport",
    "Transition",
    "WatchAdvance",
    "WatchDiff",
    "WatchSource",
    "WatchedItem",
    "advance_watch",
    "capacity",
    "cascade_cancellations",
    "audit_mid_run_edits",
    "claim_dispatch",
    "claim_dispatches",
    "cron_definitions",
    "cron_job_name",
    "crons_directory",
    "diff_poll",
    "dispatch_source",
    "dispatch_tick",
    "dispatched_generations",
    "drain_queue",
    "echo_permitted_for",
    "echoable_text",
    "elements_of_item",
    "feedback_presets",
    "forget_snapshot",
    "generation_key",
    "install_tick_script",
    "is_open_state",
    "load_route",
    "load_sources",
    "poll",
    "poll_interval_s",
    "poll_source",
    "poll_sources",
    "poll_tick",
    "poll_timeout_s",
    "record_snapshot",
    "record_name_taken",
    "record_refusal",
    "record_unmapped",
    "recorded_items",
    "release_dispatch_claim",
    "run_tick_script",
    "screening_enabled_for",
    "source_names",
    "source_of_job",
    "submitter_class_of",
    "tick_script_path",
    "class_of_author",
    "FEEDBACK_FIELD",
    "FEEDBACK_PRESET_HOSTS",
    "FEEDBACK_PRESETS",
    "FeedbackOutcome",
    "FeedbackPoster",
    "FeedbackReport",
    "load_feedback",
    "name_taken_items",
    "post_feedback",
    "release_writeback_claim",
    "unmapped_items",
    "watch_source_presets",
]
